---
- name: "Pihole | Server | Add group {{ pihole_username }}"
  group:
    name: "{{ pihole_username }}"
    state: present
- name: Pihole | Server | Find Fish location
  command: which fish
  register: fish_location
- name: "Pihole | Server | Add user {{ pihole_username }}"
  user:
    name: "{{ pihole_username }}"
    group: "{{ pihole_username }}"
    shell: "{{ fish_location.stdout }}"
    state: present
    groups: docker
    append: yes
- name: "Pihole | Server | Add SSH key for user {{ pihole_username }}"
  authorized_key:
    user: "{{ pihole_username }}"
    state: present
    key: "{{ lookup('file', '~/.ssh/raspberry_key.pub') }}"