---
- name: Install Server
  vars_files:
    - parameters.yml
  hosts: raspberry
  remote_user: "{{ py_default_user }}"
  become: true
  become_method: sudo
  tasks:
    - name: APT | Update system
      apt:
        upgrade: dist
        update_cache: yes
        autoclean: yes
    - include_role:
        name: raspberry/firewall
    - include_role:
        name: raspberry/tools