---
- name: Config | Remove Pi default user
  user:
    name: "{{ py_default_user }}"
    state: absent
    remove: yes
    force: yes
# - name: Config | Remove Swap partition
#   shell: systemctl disable dphys-swapfile.service
- name: Config | Change locale
  shell: "raspi-config nonint do_change_locale {{ py_locale }}"
- name: Config | Change timezone
  shell: "raspi-config nonint do_change_timezone {{ py_timezone }}"
- name: Config | Change Keybord layout
  shell: "raspi-config nonint do_configure_keyboard {{ py_keyboard_layout}}"
- name: Config | Expand File System
  shell: "raspi-config nonint do_expand_rootfs"
  notify: raspberry reboot
- name: Config | Reload partition table
  shell: partprobe
- name: Config | Add a Cron task to keep the raspberry updated
  cron:
    name: raspberry autoupdate
    hour: "2"
    minute: "0"
    job: "sudo apt update && sudo apt upgrade -y && sudo apt autoclean && sudo apt autoremove > /var/log/syslog "
