---
traefik_contact_mail: foo@bar.com
traefik_admin_port: 8080
traefik_http_port: 80
traefik_https_port: 443
traefik_path: "/home/{{ py_root_username }}/traefik"
# DEBUG, INFO, WARN, ERROR, FATAL, PANIC
traefik_log_level: DEBUG
traefik_dashboard_entrypoint: traefik
# traefik_network allow container to be reached from outside the lan network (with the reverse proxy)
traefik_network: web
# lan_network allow container to be reached from inside the lan network (with the docker macvlan driver)
lan_network: lan
# ethernet_interface : find your ethernet interface with ifconfig (eth0, enp3s0)
ethernet_interface: eth0
# lan_subnet : your local subnet
lan_subnet: 192.168.1.0/16
# define a range of ip for the containers connected to this network.
lan_ip_range: 192.168.1.150/26
lan_gateway: 192.168.1.254
traefik_dashboard_pwd: foobar
