---
# Ansistrano global parameters
ansistrano_deploy_to: "/home/{{ username }}/www"
ansistrano_keep_releases: 2
ansistrano_shared_paths: ["storage", "public/galeries"]
ansistrano_shared_files: [".env"]
ansistrano_before_symlink_shared_tasks_file: "{{ playbook_dir }}/{{ project_name }}/tasks/ansistrano/before_symlink.yml"
ansistrano_after_symlink_tasks_file: "{{ playbook_dir }}/{{ project_name }}/tasks/ansistrano/after_symlink.yml"

# Git parameters
ansistrano_deploy_via: git
ansistrano_git_repo: "ssh://{{ git_repo }}"
ansistrano_git_branch: master