---
- name : Docker-compose | Install dependencies
  apt:
      update_cache: yes
      name:
        - python-backports.ssl-match-hostname
        - python-pip
        - libffi-dev
      state: present
- name: Docker-compose | Install Docker-Compose
  pip:
    name: docker-compose
- name: Docker-compose | Remove useless packages from the cache
  apt:
    autoclean: yes
- name: Docker-compose | Remove dependencies that are no longer required
  apt:
    autoremove: yes