---
- name: "Bokehlicious | Server | Add group {{ username }}"
  group:
    name: "{{ username }}"
    state: present
- name: Bokehlicious | Server | Find Fish location
  command: which fish
  register: fish_location
- name: "Bokehlicious | Server | Add user {{ username }}"
  user:
    name: "{{ username }}"
    group: "{{ username }}"
    shell: "{{ fish_location.stdout }}"
    state: present
    groups: docker
    append: yes
- name: "Bokehlicious | Server | Add SSH key for user {{ username }}"
  authorized_key:
    user: "{{ username }}"
    state: present
    key: "{{ lookup('file', '~/.ssh/raspberry_key.pub') }}"
- name: "Bokehlicious | Server | Create {{project_deploy_dir }} folder"
  file:
    path: "{{project_deploy_dir}}"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0770