---
- name: Config | Raspberry user configuration tasks
  include_tasks: user.yml
- name: Config | Raspberry global configuration tasks
  include_tasks: config.yml
  args:
    apply:
        remote_user: "{{ py_root_username }}"
        become: yes
        become_method: sudo