---
- name: "Traefik | Create logs dir in {{ traefik_path }}/logs"
  file:
    path: "{{ traefik_path }}/logs"
    state: directory
    owner: "{{ py_root_username }}"
    group: "{{ py_root_username }}"
    mode: "0755"
- name: Traefik | Add docker-compose.yml
  template:
    src: templates/docker-compose.yml.j2
    dest: "/home/{{ py_root_username }}/traefik/docker-compose.yml"
    owner: "{{ py_root_username }}"
    group: "{{ py_root_username }}"
- name: Traefik | Add traefik.toml
  template:
    src: templates/traefik.toml.j2
    dest: "/home/{{ py_root_username }}/traefik/traefik.toml"
    owner: "{{ py_root_username }}"
    group: "{{ py_root_username }}"
- name: Traefik | Create acme.json
  file:
    path: "{{ traefik_path }}/acme.json"
    state: touch
    owner: "{{ py_root_username }}"
    group: "{{ py_root_username }}"
    mode: "0600"
- name: "Traefik | Check if Docker network {{traefik_network}} exist"
  command: docker network ls --format "{% raw %}{{.Name}}{% endraw %}"
  register: networks
- debug:
    var: networks
- name: Traefik | Create Docker network
  command: "docker network create {{traefik_network}}"
  when: traefik_network not in networks.stdout_lines
- name: Traefik | Start container
  command: docker-compose up -d --build --remove-orphans
  args:
    chdir: "/home/{{ py_root_username }}/traefik"
