---
# - name: Bokehlicious | Include Ansistrano variables
#   include_vars: ansistrano.yml
- name: Bokehlicious | Start deployment
  apt:
    upgrade: dist
    update_cache: yes
    autoclean: yes
- name: Bokehlicious | Configure User
  include_tasks: ./server/user.yml