---
- name: Install Traefik (reverse proxy for Docker)
  vars_files:
    - ../parameters.yml
  hosts: raspberry
  remote_user: "{{ py_root_username }}"
  become: true
  become_method: sudo
  tasks:
    - include_role:
        name: traefik
