---
  # See : https://docs.ansible.com/ansible/latest/modules/ufw_module.html
- name: Firewall | Reset previous rules
  ufw:
    state: reset
- name: Firewall | Block all incoming trafic & All outcoming trafic
  ufw:
    direction: "{{ item.direction }}"
    policy: "{{ item.policy }}"
  loop:
    - { direction: incoming, policy: deny }
    - { direction: outgoing, policy: allow }
- name: Firewall | Allow specific ports
  ufw:
    port: "{{ item.port }}"
    rule: "{{ item.permission }}"
    proto: "{{ item.proto }}"
    from: "{{ item.from }}"
  loop: "{{ firewalls_authorizes_ports }}"
# To see UFW status and rules : sudo ufw status verbose
- name: Firewall | Activate UFW
  ufw:
    state: enabled