---
- name: "Firewall | Update all packages (Debian {{ debian_codename }})"
  apt:
    upgrade: dist
- name: "Firewall | Install UFW (Debian {{ debian_codename }})"
  apt:
    update_cache: yes
    name: ufw
    state: present
- name: Firewall | Remove useless packages from the cache
  apt:
    autoclean: yes
- name: Firewall | Remove dependencies that are no longer required
  apt:
    autoremove: yes